all:
	g++ -o string   string.cpp   -std=c++11 -lpthread
	g++ -o vector   vector.cpp   -std=c++11 -lpthread
	g++ -o deque    deque.cpp    -std=c++11 -lpthread
	g++ -o stack    stack.cpp    -std=c++11 -lpthread
	g++ -o queue    queue.cpp    -std=c++11 -lpthread
	g++ -o list     list.cpp     -std=c++11 -lpthread
	g++ -o set      set.cpp      -std=c++11 -lpthread
	g++ -o multiset multiset.cpp -std=c++11 -lpthread
	g++ -o map      map.cpp      -std=c++11 -lpthread
	g++ -o multimap multimap.cpp -std=c++11 -lpthread
	g++ -o container_comm container_comm.cpp -std=c++11 -lpthread
clean:
	rm  -rf string
	rm  -rf vector
	rm  -rf deque
	rm  -rf stack
	rm  -rf queue
	rm  -rf list
	rm  -rf set
	rm  -rf multiset
	rm  -rf map
	rm  -rf multimap
	rm  -rf container_comm