all:
	g++ -o polymorphism1 polymorphism1.cpp -std=c++11 -lpthread
	g++ -o polymorphism2 polymorphism2.cpp -std=c++11 -lpthread
	g++ -o polymorphism3 polymorphism3.cpp -std=c++11 -lpthread
clean:
	rm -rf polymorphism1
	rm -rf polymorphism2
	rm -rf polymorphism3
