all:
	g++ -o io_stream1  io_stream1.cpp  -std=c++11 -lpthread
	g++ -o io_stream2  io_stream2.cpp  -std=c++11 -lpthread
	g++ -o io_stream3  io_stream3.cpp  -std=c++11 -lpthread
	g++ -o io_stream4  io_stream4.cpp  -std=c++11 -lpthread
clean:
	rm  -rf io_stream1
	rm  -rf io_stream2
	rm  -rf io_stream3
	rm  -rf io_stream4