all:
	g++ -o thread1  thread1.cpp  -std=c++11 -lpthread
	g++ -o thread2  thread2.cpp  -std=c++11 -lpthread
	g++ -o thread3  thread3.cpp  -std=c++11 -lpthread
	g++ -o atomic1  atomic1.cpp  -std=c++11 -lpthread
	g++ -o condition1  condition1.cpp  -std=c++11 -lpthread
	g++ -o condition2  condition2.cpp  -std=c++11 -lpthread
clean:
	rm  -rf thread1
	rm  -rf thread2
	rm  -rf thread3
	rm  -rf atomic1
	rm  -rf condition1
	rm  -rf condition2