all:
	g++ -o sharedptr1  sharedptr1.cpp  -std=c++11 -lpthread
	g++ -o sharedptr2  sharedptr2.cpp  -std=c++11 -lpthread
	g++ -o sharedptr3  sharedptr3.cpp  -std=c++11 -lpthread
	g++ -o sharedptr4  sharedptr4.cpp  -std=c++11 -lpthread
	g++ -o unique_ptr1 unique_ptr1.cpp -std=c++11 -lpthread
	g++ -o weak_ptr1   weak_ptr1.cpp   -std=c++11 -lpthread
clean:
	rm  -rf sharedptr1
	rm  -rf sharedptr2
	rm  -rf sharedptr3
	rm  -rf sharedptr4
	rm  -rf unique_ptr1
	rm  -rf weak_ptr1